/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Javicuc
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        ImageIcon img = new ImageIcon("Images/logo.png");
        setUndecorated(true);
        setResizable(true);
        setVisible(true);
        
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        this.setSize(xsize,ysize);
        LBL_Icon.setIcon(img);
        LBL_Icon.setHorizontalAlignment(JLabel.CENTER);
        LBL_Icon.setVerticalAlignment(JLabel.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LBL_Icon = new javax.swing.JLabel();
        panelBarButtons = new javax.swing.JPanel();
        btProductos = new javax.swing.JButton();
        btVentas = new javax.swing.JButton();
        btCorte = new javax.swing.JButton();
        btEmpleados = new javax.swing.JButton();
        btInventario = new javax.swing.JButton();
        btProveedores = new javax.swing.JButton();
        btClientes = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        panelBarUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        btSession = new javax.swing.JButton();
        panelViews = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(LBL_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1402, 192));

        panelBarButtons.setBackground(new java.awt.Color(204, 204, 204));
        panelBarButtons.setLayout(new java.awt.GridBagLayout());

        btProductos.setText("PRODUCTOS");
        btProductos.setFocusable(false);
        btProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 3, 0);
        panelBarButtons.add(btProductos, gridBagConstraints);

        btVentas.setText("VENTAS");
        btVentas.setFocusable(false);
        btVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 3, 0);
        panelBarButtons.add(btVentas, gridBagConstraints);

        btCorte.setText("CORTE");
        btCorte.setFocusable(false);
        btCorte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCorte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btCorte, gridBagConstraints);

        btEmpleados.setText("EMPLEADOS");
        btEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpleadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btEmpleados, gridBagConstraints);

        btInventario.setText("INVENTARIO");
        btInventario.setFocusable(false);
        btInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btInventario, gridBagConstraints);

        btProveedores.setText("PROVEEDORES");
        btProveedores.setFocusable(false);
        btProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProveedoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btProveedores, gridBagConstraints);

        btClientes.setText("CLIENTES");
        btClientes.setFocusable(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btClientes, gridBagConstraints);

        btConfiguracion.setText("CONFIGURACION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 3, 0);
        panelBarButtons.add(btConfiguracion, gridBagConstraints);

        getContentPane().add(panelBarButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1370, 60));

        panelBarUser.setBackground(new java.awt.Color(204, 204, 204));
        panelBarUser.setLayout(new java.awt.GridBagLayout());

        lblUser.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 417;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        panelBarUser.add(lblUser, gridBagConstraints);

        btExit.setText("SALIR");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        panelBarUser.add(btExit, gridBagConstraints);

        btSession.setText("CERRAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        panelBarUser.add(btSession, gridBagConstraints);

        getContentPane().add(panelBarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 650, -1));

        javax.swing.GroupLayout panelViewsLayout = new javax.swing.GroupLayout(panelViews);
        panelViews.setLayout(panelViewsLayout);
        panelViewsLayout.setHorizontalGroup(
            panelViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        panelViewsLayout.setVerticalGroup(
            panelViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(panelViews, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1380, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductosActionPerformed
        ArticuloView viewArticulo = null;
        try {
           viewArticulo  = new ArticuloView();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelViews.removeAll();
        panelViews.updateUI();
        viewArticulo.getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        panelViews.add(viewArticulo.getContentPane(),BorderLayout.CENTER);
        
    }//GEN-LAST:event_btProductosActionPerformed

    private void btProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProveedoresActionPerformed
        ProveedoresView view = null;
        try {
           view  = new ProveedoresView();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelViews.removeAll();
        panelViews.updateUI();
        view.getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        panelViews.add(view.getContentPane(),BorderLayout.CENTER);
        
    }//GEN-LAST:event_btProveedoresActionPerformed

    private void btEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpleadosActionPerformed
        EmpleadoView view = null;
        try {
           view  = new EmpleadoView();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelViews.removeAll();
        panelViews.updateUI();
        view.getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        panelViews.add(view.getContentPane(),BorderLayout.CENTER);
        
    }//GEN-LAST:event_btEmpleadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_Icon;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btCorte;
    private javax.swing.JButton btEmpleados;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btInventario;
    private javax.swing.JButton btProductos;
    private javax.swing.JButton btProveedores;
    private javax.swing.JButton btSession;
    private javax.swing.JButton btVentas;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelBarButtons;
    private javax.swing.JPanel panelBarUser;
    private javax.swing.JPanel panelViews;
    // End of variables declaration//GEN-END:variables
}
